
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ahsan
 */
public class SalesReturn extends javax.swing.JFrame {

    /**
     * Creates new form SalesReturn
     */
    public SalesReturn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtComName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPricePerUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPercentage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtExp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAvailableQty = new javax.swing.JLabel();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 93, 32));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setText("Sales Return ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 257, 32));
        getContentPane().add(txtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Product Description :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 30));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 370, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Company Name        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, 20));
        getContentPane().add(txtComName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 370, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Price Per Unit             :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 180, 30));
        getContentPane().add(txtPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 370, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Quantity                      :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 190, 30));

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 370, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Total                             :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 180, 30));

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 0, 51));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 370, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Percentage                 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 180, 30));

        txtPercentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPercentageKeyReleased(evt);
            }
        });
        getContentPane().add(txtPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 370, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, -1, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Exp.Date                      :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, 30));

        txtExp.setForeground(new java.awt.Color(153, 0, 51));
        getContentPane().add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 370, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Available QTY :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 58));

        txtAvailableQty.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtAvailableQty.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(txtAvailableQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 70, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int checkMedicineExist = 0;
        String batch = txtBatch.getText().trim();

        if (batch.equals("")) {
            JOptionPane.showMessageDialog(null, "Batch name is required!");
        } else {
            try {
                Connection con = ConnectionProvider.getCon();
                String query = "SELECT * FROM medicine WHERE  batch = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, batch);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txtName.setText(rs.getString("name"));
                    txtExp.setText(rs.getString("expDate"));
                    txtComName.setText(rs.getString("companyName"));
                    txtPricePerUnit.setText(rs.getString("price"));
                    txtAvailableQty.setText(rs.getString("quantity"));
                    //  txtQuantity.setText(rs.getString("quantity"));

                    txtName.setEditable(true);
                    txtQuantity.setEditable(true);
                    checkMedicineExist = 1;
                }

                if (checkMedicineExist == 0) {
                    JOptionPane.showMessageDialog(null, "Medicine does not exist!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String avalableQty = txtAvailableQty.getText();
        String batch = txtBatch.getText().trim();
        String quantity = txtQuantity.getText();

        // String quantity = txtQuantity.getText();
        int totalQuantity = 0;
        if (quantity.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Current quantity is missing!");
            return;
        }

        try {
            int currentQuantity = Integer.parseInt(quantity);
            if (quantity.isEmpty()) {
                totalQuantity = currentQuantity;
            } else {
                totalQuantity = currentQuantity + Integer.parseInt(avalableQty);
            }

            Connection con = ConnectionProvider.getCon();
            String query = "UPDATE medicine SET  quantity = ? WHERE batch = ?";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setInt(1, totalQuantity);
            pst.setString(2, batch);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Medicine Updated Successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Medicine not found!");
            }

            setVisible(false);
            new SalesReturn().setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Quantity must be a valid number!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        String Quantity = txtQuantity.getText();
        String price = txtPricePerUnit.getText();

        int totalPrice = Integer.parseInt(Quantity) * Integer.parseInt(price);
        txtTotal.setText(String.valueOf(totalPrice));


    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtPercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPercentageKeyReleased
        // TODO add your handling code here:

        String percentage = txtPercentage.getText(); // Assuming you have a JTextField named txtPercentage
        String price = txtPricePerUnit.getText();
        String quantity = txtQuantity.getText();

        try {
            int qty = Integer.parseInt(quantity);
            int unitPrice = Integer.parseInt(price);
            int totalPrice = qty * unitPrice;

            if (!percentage.isEmpty()) {
                double discount = Double.parseDouble(percentage) / 100.0;
                totalPrice = (int) (totalPrice * (1 - discount)); // Applying the discount percentage
            }

            txtTotal.setText(String.valueOf(totalPrice));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Quantity, Price, and Percentage!");
        }


    }//GEN-LAST:event_txtPercentageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtAvailableQty;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtComName;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPercentage;
    private javax.swing.JTextField txtPricePerUnit;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
