/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.ConnectionProvider;
   import javax.swing.JOptionPane;
   import java.sql.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author ahsan
 */
public class Withdraw extends javax.swing.JFrame {
    
    public String numberPattern ="^[0-9]*$";
    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtIssuedBy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIssuedTo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        dateOfWithdraw = new com.toedter.calendar.JDateChooser();

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Pharmacy management tools\\Pharmacy Management System Images & Pattern\\Pharmacy Management System Images & Pattern\\close.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setLocation(new java.awt.Point(200, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Withdraw");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 28, 214, 57));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 1472, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Issued By");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 155, -1));

        txtIssuedBy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtIssuedBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Issued To ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 205, -1));

        txtIssuedTo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtIssuedTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Mobile No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 96, -1));

        txtMobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 162, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 90, 44));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Reason");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Pharmacy management tools\\Pharmacy Management System Images & Pattern\\Pharmacy Management System Images & Pattern\\save.png")); // NOI18N
        jButton2.setText("Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        txtReason.setColumns(20);
        txtReason.setRows(5);
        jScrollPane1.setViewportView(txtReason);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 280, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Date :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 80, 20));
        getContentPane().add(dateOfWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 310, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String reason =txtReason.getText();
        String issuedBy=txtIssuedBy.getText();
        String amount=txtAmount.getText();
        String issuedTo =txtIssuedTo.getText();
        String mobile =txtMobile.getText();
        String address=txtAddress.getText();
       
        
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    java.util.Date date = dateOfWithdraw.getDate();
    String Date = "";
    if (date != null) {
        Date = dFormat.format(date);
    }
        
        
        
        
        
        if (reason.equals("")){
            JOptionPane.showMessageDialog(null,"Reason is required!");
        }else if (issuedBy.equals("")){
            JOptionPane.showMessageDialog(null,"Issued By field is required!");
        }else if (amount.equals("")){
            JOptionPane.showMessageDialog(null,"Amount field is required!");
        }else if (issuedTo.equals("")){
            JOptionPane.showMessageDialog(null,"Issued To field is required!");
        }else if (mobile.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile No field is required!");
        }else if (!mobile.matches(numberPattern)){
            JOptionPane.showMessageDialog(null,"Mobile number is invalid!");
        }else if(Date.equals("")){
            JOptionPane.showMessageDialog(null,"Date field is required!");
        }
        
        
        else{
            try{
            Connection con =ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into withdraw(reason,issuedBy,issuedTo,amount,mobile,address,date) values(?,?,?,?,?,?,?) ");
            ps.setString(1,reason);
            ps.setString(2,issuedBy);
            ps.setString(3,issuedTo);
            ps.setString(4,amount);
            ps.setString(5,mobile);
            ps.setString(6,address);
            ps.setString(7,Date);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Withdraw Saved.");
            new Withdraw().setVisible(true);
            
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateOfWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtIssuedBy;
    private javax.swing.JTextField txtIssuedTo;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextArea txtReason;
    // End of variables declaration//GEN-END:variables
}
